// Small typed fetch client for the real ASP.NET Core API. Every call is
// typed against src/api/types.ts, generated by hand from the running
// backend's OpenAPI document plus its DTO source.
import type {
  DepotDto, DriverDto, ExceptionDto, ExceptionStatus, LoginResponse, MetaDto,
  OverviewDto, RouteDto, RouteStatus, ScheduleEntryDto, ShipmentDto, VehicleDto, PagedResult, ApiErrorBody,
  HealthDto, SeedSummaryDto,
} from './types.ts';

// Build-time configurable API origin (VITE_API_BASE_URL). Empty (default)
// keeps relative /api/* requests routed through vite.config.ts's dev proxy
// (dev) or the deployed reverse proxy (prod). Set to an absolute URL (e.g.
// http://localhost:5269) to call the API directly. Trailing slashes are
// normalized away so `${apiBaseUrl}/api/<path>` is always well-formed.
const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/+$/, '');

export class ApiError extends Error {
  status: number;
  body: ApiErrorBody | null;
  constructor(status: number, body: ApiErrorBody | null) {
    super(body?.message ?? `Request failed with status ${status}`);
    this.status = status;
    this.body = body;
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${apiBaseUrl}/api${path}`, {
    ...init,
    headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) },
  });
  if (!response.ok) {
    let body: ApiErrorBody | null = null;
    try { body = await response.json(); } catch { /* non-JSON error body */ }
    throw new ApiError(response.status, body);
  }
  if (response.status === 204) return undefined as T;
  return (await response.json()) as T;
}

function authHeaders(token: string | null): HeadersInit | undefined {
  return token ? { authorization: `Bearer ${token}` } : undefined;
}

// The health endpoint intentionally returns 503 when unhealthy (correct HTTP
// semantics, and what a real Azure health probe checks) — the /health page
// needs the response BODY either way, not an ApiError thrown on a non-2xx
// status, so this bypasses request()'s throw-on-!ok behavior.
async function fetchHealth(path: string): Promise<HealthDto> {
  const response = await fetch(`${apiBaseUrl}${path}`, { headers: { 'content-type': 'application/json' } });
  return (await response.json()) as HealthDto;
}

export const api = {
  getOverview: () => request<OverviewDto>('/overview'),
  getApiHealth: () => fetchHealth('/api/health'),
  getMeta: () => request<MetaDto>('/meta'),
  getRoutes: (status?: RouteStatus) => request<RouteDto[]>(`/routes${status ? `?status=${status}` : ''}`),
  getVehicles: () => request<VehicleDto[]>('/vehicles'),
  getDrivers: () => request<DriverDto[]>('/drivers'),
  getDepots: () => request<DepotDto[]>('/depots'),
  getShipments: (params: { status?: string; routeId?: string; page?: number; pageSize?: number } = {}) => {
    const query = new URLSearchParams();
    if (params.status) query.set('status', params.status);
    if (params.routeId) query.set('routeId', params.routeId);
    if (params.page) query.set('page', String(params.page));
    if (params.pageSize) query.set('pageSize', String(params.pageSize));
    const suffix = query.toString() ? `?${query.toString()}` : '';
    return request<PagedResult<ShipmentDto>>(`/shipments${suffix}`);
  },
  getExceptions: (status?: string, severity?: string) => {
    const query = new URLSearchParams();
    if (status) query.set('status', status);
    if (severity) query.set('severity', severity);
    const suffix = query.toString() ? `?${query.toString()}` : '';
    return request<ExceptionDto[]>(`/exceptions${suffix}`);
  },
  getSchedule: (from?: string, to?: string) => {
    const query = new URLSearchParams();
    if (from) query.set('from', from);
    if (to) query.set('to', to);
    const suffix = query.toString() ? `?${query.toString()}` : '';
    return request<ScheduleEntryDto[]>(`/schedule${suffix}`);
  },

  login: (email: string, password: string) =>
    request<LoginResponse>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }),

  patchExceptionStatus: (id: string, status: ExceptionStatus, token: string) =>
    request<ExceptionDto>(`/exceptions/${id}/status`, {
      method: 'PATCH', headers: authHeaders(token), body: JSON.stringify({ status }),
    }),
  patchSchedule: (id: string, body: { shiftStart?: string; shiftEnd?: string; routeId?: string | null; status?: string }, token: string) =>
    request<ScheduleEntryDto>(`/schedule/${id}`, { method: 'PATCH', headers: authHeaders(token), body: JSON.stringify(body) }),
  patchRouteDriver: (id: string, driverId: string, vehicleId: string | null, token: string) =>
    request<RouteDto>(`/routes/${id}/driver`, { method: 'PATCH', headers: authHeaders(token), body: JSON.stringify({ driverId, vehicleId }) }),

  // Restores the fixed demo baseline, undoing any writes made this session (exception status,
  // schedule edits, route reassignment) that the UI itself has no way to revert. Gated by the
  // same JWT auth as every other write endpoint — never reachable from the public session.
  resetDemoData: (token: string) =>
    request<SeedSummaryDto>('/admin/reset-data', { method: 'POST', headers: authHeaders(token) }),
};
