// Typed shapes generated by hand from the running API's OpenAPI document
// (GET /openapi/v1.json) and backend/src/Application/Dtos/Dtos.cs. Field
// names/casing match the real JSON responses exactly (verified against a
// running instance), not guessed from the C# record names.

export type RouteStatus = 'Planned' | 'InProgress' | 'Completed' | 'Delayed';
export type VehicleStatus = 'Active' | 'Maintenance' | 'OutOfService';
export type DriverStatus = 'OnShift' | 'OffShift' | 'OnBreak';
export type ShipmentStatus = 'Pending' | 'Dispatched' | 'InTransit' | 'Delivered' | 'Exception';
export type ExceptionKind = 'SlaRisk' | 'SlaBreach' | 'FailedAttempt' | 'Damaged' | 'AddressIssue';
export type ExceptionSeverity = 'Low' | 'Medium' | 'High';
export type ExceptionStatus = 'Open' | 'Investigating' | 'Resolved' | 'Escalated';
export type ScheduleStatus = 'Scheduled' | 'Confirmed' | 'Conflict';

export interface VehicleDto { id: string; label: string; type: string; capacity: number; status: VehicleStatus; homeDepotId: string; }
export interface DriverDto { id: string; name: string; status: DriverStatus; vehicleId: string | null; territory: string; }
export interface DepotDto { id: string; name: string; lat: number; lng: number; }
export interface RouteStopDto { id: string; routeId: string; sequence: number; lat: number; lng: number; shipmentId: string | null; }
export interface RouteDto {
  id: string; label: string; driverId: string; vehicleId: string; depotId: string;
  plannedStart: string; plannedEnd: string; status: RouteStatus; stops: RouteStopDto[];
}
export interface ShipmentDto {
  id: string; routeId: string | null; customerLabel: string; originDepotId: string;
  destinationLat: number; destinationLng: number; slaWindowStart: string; slaWindowEnd: string;
  status: ShipmentStatus; plannedEta: string; actualDeliveredAt: string | null; slaState: string;
}
export interface PagedResult<T> { items: T[]; total: number; page: number; pageSize: number; }
export interface ExceptionDto {
  id: string; shipmentId: string; customerLabel: string; kind: ExceptionKind; severity: ExceptionSeverity;
  openedAt: string; status: ExceptionStatus; note: string;
}
export interface ScheduleEntryDto {
  id: string; driverId: string; shiftStart: string; shiftEnd: string; routeId: string | null; status: ScheduleStatus;
}
export interface OnTimeTrendPointDto { date: string; onTimeRate: number; }
export interface ExceptionSeverityBucketDto { severity: ExceptionSeverity; count: number; }
export interface OverviewDto {
  onTimeRate: number; otifRate: number; activeExceptionCount: number; fleetUtilization: number;
  onTimeTrend: OnTimeTrendPointDto[]; exceptionsBySeverity: ExceptionSeverityBucketDto[];
}
export interface MetaDto { datasetVersion: string; scenarioClockReference: string; seededAt: string; }
export interface LoginResponse { token: string; expiresAt: string; }
export interface ApiErrorBody { error: string; message: string; }
export type HealthStatus = 'Healthy' | 'Degraded' | 'Unhealthy';
export interface HealthCheckEntryDto {
  name: string; status: HealthStatus; description: string | null; durationMs: number; error: string | null;
}
export interface HealthDto {
  status: HealthStatus; service: string; version: string; environment: string;
  uptimeSeconds: number; timestamp: string; totalDurationMs: number; checks: HealthCheckEntryDto[];
}
export interface SeedSummaryDto {
  datasetVersion: string; seededAt: string; depots: number; vehicles: number; drivers: number;
  routes: number; routeStops: number; shipments: number; exceptions: number; scheduleEntries: number;
}
